name: Build and deploy Python app to Azure Web App - KoBotzky

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'  # Zmieniamy na obsługiwaną wersję
  AZURE_WEBAPP_NAME: 'KoBotzky'
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # Nie używamy już zipowania

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48F49FDD32DF4F75A37CAE0B50807600 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D8D587078C564ED99FF2B4CC08ED7A1B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A981C6FC84604FD982946B63E130BCC6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          runtime-stack: 'PYTHON|3.9'
          startup-command: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'
